version: "3.7"

services:
  db:
    container_name: db
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/home/user/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    volumes:
      - ./frontend:/home/user/app
      - /home/user/app/node_modules
      - /home/user/app/.next
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
