version: "3.7"

services:
  db:
    container_name: db
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    volumes:
      - ./backend:/home/user/app
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: frontend
    ports:
      - "3001:3001"
    env_file:
      - ./.env.dev
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    restart: unless-stopped

volumes:
  postgres_data:
