version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - db
  db:
    image: postgres:11.3-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      API_URL: ${API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
