version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
  aws-ecs: circleci/aws-ecs@1.1.0

branches-to-test: &branches-to-test
  filters:
    branches:
      only:
        - master
        - develop
        - deploy

branches-to-deploy: &branches-to-deploy
  filters:
    branches:
      only:
        - master
        - develop
        - deploy

commands:
  update-submodules:
    steps:
      - checkout
      - run:
          name: "Update submodules"
          command: git submodule update --init --recursive

jobs:
  test-backend:
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - update-submodules
      - run:
          name: "Run type-check and tests"
          command: >
            cd backend &&
            docker-compose -f docker-compose.circleci.yml
            run --rm backend sh -c "mypy . && pytest tests"

  test-frontend:
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - update-submodules
      - run:
          name: "Run type-check and linting"
          command: >
            cd frontend &&
            docker-compose -f docker-compose.circleci.yml
            run --rm frontend sh -c "yarn type-check && yarn lint"

workflows:
  deploy:
    jobs:
      - test-backend:
          <<: *branches-to-deploy
      - test-frontend:
          <<: *branches-to-deploy
      - aws-ecr/build-and-push-image:
          name: build-backend
          requires:
            - test-backend
          pre-steps:
            - update-submodules
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: ./backend/Dockerfile.prod
          region: AWS_REGION
          repo: backend
          tag: "${CIRCLE_SHA1}"
          <<: *branches-to-deploy

      - aws-ecr/build-and-push-image:
          name: build-frontend
          requires:
            - test-frontend
          pre-steps:
            - update-submodules
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: ./frontend/Dockerfile.prod
          region: AWS_REGION
          repo: frontend
          tag: "${CIRCLE_SHA1}"
          <<: *branches-to-deploy

      - aws-ecs/update-task-definition-from-json:
          requires:
            - build-backend
            - build-frontend
          pre-steps:
            - checkout
          task-definition-json: task-definition.json
          <<: *branches-to-deploy

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecs/update-task-definition-from-json
          aws-region: AWS_DEFAULT_REGION
          family: skole-task
          cluster-name: skole-cluster
          container-image-name-updates: "container=backend,tag=${CIRCLE_SHA1},container=frontend,tag=${CIRCLE_SHA1}"
          <<: *branches-to-deploy
