version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@1.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          pre-steps:
            - checkout
            - run:
                command: |
                  git submodule init
                  git submodule update --remote
          account-url: AWS_ACCOUNT_URL
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          region: AWS_DEFAULT_REGION
          tag: '${CIRCLE_SHA1}'
          path: backend
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_DEFAULT_REGION
          family: '${AWS_RESOURCE_NAME_PREFIX}-service'
          cluster-name: '${AWS_RESOURCE_NAME_PREFIX}-cluster'
          container-image-name-updates: 'container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}'
