version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
  aws-ecs: circleci/aws-ecs@1.1.0


prod-branch: &prod-branch
  filters:
    branches:
      only:
        - master

staging-branch: &staging-branch
  filters:
    branches:
      only:
        - develop

build-image: &build-image
  pre-steps:
    - update-submodules
  account-url: AWS_ECR_ACCOUNT_URL
  aws-access-key-id: AWS_ACCESS_KEY_ID
  aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  region: AWS_REGION
  tag: "${CIRCLE_SHA1}"

update-service: &update-service
  aws-region: AWS_DEFAULT_REGION
  container-image-name-updates: "container=backend,tag=${CIRCLE_SHA1},container=frontend,tag=${CIRCLE_SHA1}"


commands:
  update-submodules:
    steps:
      - checkout
      - run:
          name: "Update submodules"
          command: git submodule update --init --recursive


jobs:
  test-backend:
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - update-submodules
      - run:
          name: "Run type-check and tests"
          command: >
            cd backend &&
            docker-compose -f docker-compose.circleci.yml
            run --rm backend sh -c "mypy . && pytest tests"

  test-frontend:
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - update-submodules
      - run:
          name: "Run type-check and linting"
          command: >
            cd frontend &&
            docker-compose -f docker-compose.circleci.yml
            run --rm frontend sh -c "yarn type-check && yarn lint"


workflows:
  deploy:
    jobs:
      # Production deployment workflow
      - test-backend:
          <<: *prod-branch
      - test-frontend:
          <<: *prod-branch

      - aws-ecr/build-and-push-image:
          name: build-backend
          dockerfile: backend/Dockerfile.prod
          path: backend
          repo: backend
          <<: *build-image
          <<: *prod-branch

      - aws-ecr/build-and-push-image:
          name: build-frontend
          dockerfile: frontend/Dockerfile.prod
          path: frontend
          repo: frontend
          context: frontend-prod-env
          extra-build-args: &frontend-build-args "--build-arg API_URL --build-arg BACKEND_URL --build-arg CLOUDMERSIVE_API_KEY"
          <<: *build-image
          <<: *prod-branch

      - aws-ecs/update-task-definition-from-json:
          name: update-prod-task-definition
          requires:
            - test-backend
            - test-frontend
            - build-backend
            - build-frontend
          pre-steps:
            - checkout
          task-definition-json: task-definition.json
          <<: *prod-branch

      - aws-ecs/deploy-service-update:
          name: update-prod-service
          requires:
            - update-prod-task-definition
          cluster-name: skole-cluster
          service-name: skole-service
          family: skole-task
          <<: *update-service
          <<: *prod-branch

      # Staging deployment workflow
      - aws-ecr/build-and-push-image:
          name: build-staging-backend
          dockerfile: backend/Dockerfile.prod
          path: backend
          repo: backend-staging
          <<: *build-image
          <<: *staging-branch

      - aws-ecr/build-and-push-image:
          name: build-staging-frontend
          dockerfile: frontend/Dockerfile.prod
          path: frontend
          repo: frontend-staging
          context: frontend-staging-env
          extra-build-args: *frontend-build-args
          <<: *build-image
          <<: *staging-branch

      - aws-ecs/update-task-definition-from-json:
          name: update-staging-task-definition
          requires:
            - build-staging-backend
            - build-staging-frontend
          pre-steps:
            - checkout
          task-definition-json: task-definition-staging.json
          <<: *staging-branch

      - aws-ecs/deploy-service-update:
          name: update-staging-service
          requires:
            - update-staging-task-definition
          cluster-name: skole-staging-cluster
          service-name: skole-staging-service
          family: skole-staging-task
          <<: *update-service
          <<: *staging-branch
