version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.2.0


# Custom YAML anchors

prod-branch: &prod-branch
  filters:
    branches:
      only:
        - master

staging-branch: &staging-branch
  filters:
    branches:
      only:
        - develop

build-image: &build-image
  executor: machine-with-cache
  pre-steps:
    - update-submodules
  dockerfile: Dockerfile
  account-url: AWS_ECR_ACCOUNT_URL
  aws-access-key-id: AWS_ACCESS_KEY_ID
  aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  region: AWS_REGION
  tag: "${CIRCLE_SHA1}"

verify-deployment: &verify-deployment
   max-poll-attempts: 90
   poll-interval: 10
   task-definition-arn: "${TASK_DEFINITION_ARN}"


# CircleCI's own sections

executors:
  machine-with-cache:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

  docker-no-cache:
    docker:
      - image: cimg/base:2020.01
    resource_class: small

commands:
  update-submodules:
    steps:
      - checkout
      - run:
          name: "Update submodules"
          command: git submodule update --init --recursive

jobs:
  check-commits:
    executor: docker-no-cache
    steps:
      - update-submodules
      - run:
          name: "Check commits of the PR branch"
          command: ./.circleci/check_commits.sh
      - run:
          name: "Check submodule commit branches"
          command: ./.circleci/check_submodules.sh

workflows:
  check-commits:
    jobs:
      - check-commits:
          filters:
            branches:
              ignore:
                - master
                - develop

  deploy-prod:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build-prod-backend
          repo: backend-prod
          path: backend
          <<: *build-image
          <<: *prod-branch

      - aws-ecr/build-and-push-image:
          name: build-prod-frontend
          repo: frontend-prod
          path: frontend
          context: prod
          extra-build-args: "--build-arg API_URL --build-arg FRONTEND_URL --build-arg SA_URL --build-arg EMAIL_ADDRESS"
          <<: *build-image
          <<: *prod-branch

      - aws-ecs/deploy-service-update:
          name: update-prod-service
          requires:
            - build-prod-backend
            - build-prod-frontend
          cluster-name: skole-prod-cluster
          service-name: skole-prod-service
          family: skole-prod-task
          aws-region: $AWS_REGION
          container-image-name-updates: "container=backend_prod,tag=${CIRCLE_SHA1},container=frontend_prod,tag=${CIRCLE_SHA1}"
          <<: *prod-branch
          post-steps:
            - run:
                name: "Get latest task definition arn"
                command: >
                  TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                      --task-definition skole-prod-task \
                      --output text \
                      --query "taskDefinition.taskDefinitionArn")
                  echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
                  $BASH_ENV
            - aws-ecs/verify-revision-is-deployed:
                cluster-name: skole-prod-cluster
                service-name: skole-prod-service
                family: skole-prod-task
                <<: *verify-deployment

  deploy-staging:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build-staging-backend
          repo: backend-staging
          path: backend
          <<: *build-image
          <<: *staging-branch

      - aws-ecr/build-and-push-image:
          name: build-staging-frontend
          repo: frontend-staging
          path: frontend
          context: staging
          extra-build-args: "--build-arg API_URL --build-arg FRONTEND_URL --build-arg EMAIL_ADDRESS"
          <<: *build-image
          <<: *staging-branch

      - aws-ecs/deploy-service-update:
          name: update-staging-service
          requires:
            - build-staging-backend
            - build-staging-frontend
          cluster-name: skole-staging-cluster
          service-name: skole-staging-service
          family: skole-staging-task
          aws-region: $AWS_REGION
          container-image-name-updates: "container=backend_staging,tag=${CIRCLE_SHA1},container=frontend_staging,tag=${CIRCLE_SHA1}"
          <<: *staging-branch
          post-steps:
            - run:
                name: "Get latest task definition arn"
                command: >
                  TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                      --task-definition skole-staging-task \
                      --output text \
                      --query "taskDefinition.taskDefinitionArn")
                  echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
                  $BASH_ENV
            - aws-ecs/verify-revision-is-deployed:
                cluster-name: skole-staging-cluster
                service-name: skole-staging-service
                family: skole-staging-task
                <<: *verify-deployment
