apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-staging
spec:
  selector:
    matchLabels:
      name: backend-staging
  template:
    metadata:
      labels:
        name: backend-staging
    spec:
      containers:
        - name: backend-staging
          image: $BACKEND_IMAGE_URL
          ports:
          - containerPort: 8000
          env:
          - name: ALLOWED_HOSTS
            value: $ALLOWED_HOSTS
          - name: AWS_ACCESS_KEY_ID
            value: $STAGING_ACCESS_KEY_ID
          - name: AWS_REGION
            value: $REGION
          - name: AWS_S3_BUCKET_NAME
            value: $STAGING_S3_BUCKET_NAME
          - name: AWS_S3_BUCKET_NAME_STATIC
            value: $STAGING_S3_BUCKET_NAME_STATIC
          - name: AWS_SECRET_ACCESS_KEY
            value: $STAGING_SECRET_ACCESS_KEY
          - name: CLOUDMERSIVE_API_KEY
            value: $CLOUDMERSIVE_API_KEY
          - name: CORS_ALLOWED_ORIGIN_REGEXES
            value: $STAGING_CORS_ALLOWED_ORIGIN_REGEXES
          - name: DATABASE_URL
            value: $STAGING_DATABASE_URL
          - name: DJANGO_SETTINGS_MODULE
            value: $DJANGO_SETTINGS_MODULE
          - name: EMAIL_ADDRESS
            value: $STAGING_EMAIL_ADDRESS
          - name: EMAIL_CONTACT_FORM_SENDER
            value: $STAGING_EMAIL_CONTACT_FORM_SENDER
          - name: FCM_SERVER_KEY
            value: $FCM_SERVER_KEY
          - name: SECRET_KEY
            value: $STAGING_SECRET_KEY
